spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_ADDRESS}
    password: ${MAIL_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
  url:
    base: ${BASE_URL}